"""Add TagStatistics and BatchJobState tables

Revision ID: ca937f34246e
Revises: dce02759d2f2
Create Date: 2026-01-24 08:22:48.274460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca937f34246e'
down_revision = 'dce02759d2f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_job_state',
    sa.Column('job_name', sa.String(length=50), nullable=False),
    sa.Column('last_processed_id', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('job_name')
    )
    op.create_table('tag_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=255), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_statistics_id'), 'tag_statistics', ['id'], unique=False)
    op.create_index(op.f('ix_tag_statistics_tag'), 'tag_statistics', ['tag'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tag_statistics_tag'), table_name='tag_statistics')
    op.drop_index(op.f('ix_tag_statistics_id'), table_name='tag_statistics')
    op.drop_table('tag_statistics')
    op.drop_table('batch_job_state')
    # ### end Alembic commands ###
