"""Add tags JSONB column to documents

Revision ID: dce02759d2f2
Revises: 12afaa05449e
Create Date: 2026-01-24 02:36:39.988072

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dce02759d2f2'
down_revision = '12afaa05449e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###
    
    # Add GIN index for efficient JSONB queries
    op.create_index(
        'idx_documents_tags_gin',
        'documents',
        ['tags'],
        unique=False,
        postgresql_using='gin'
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_documents_tags_gin', table_name='documents')
    op.drop_column('documents', 'tags')
    # ### end Alembic commands ###
